# Generated by Django 3.0.7 on 2020-12-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundMain',
            fields=[
                ('main_code', models.CharField(default='', help_text='基金主体代码', max_length=12, primary_key=True, serialize=False, verbose_name='基金主体代码')),
                ('name', models.CharField(default='', help_text='基金名称', max_length=100, verbose_name='基金名称')),
                ('advisor', models.CharField(default='', help_text='基金管理人', max_length=100, verbose_name='基金管理人')),
                ('trustee', models.CharField(default='', help_text='基金托管人', max_length=100, verbose_name='基金托管人')),
                ('operate_mode_id', models.IntegerField(choices=[(401001, '开放式基金'), (401002, '封闭式基金'), (401003, 'QDII'), (401004, 'FOF'), (401005, 'ETF'), (401006, 'LOF')], help_text='基金运作方式代码', verbose_name='基金运作方式代码')),
                ('operate_mode', models.CharField(default='', help_text='基金运作方式', max_length=32, verbose_name='基金运作方式')),
                ('underlying_asset_type_id', models.IntegerField(choices=[(402001, '股票型'), (402002, '货币型'), (402003, '债券型'), (402004, '混合型'), (402005, '基金型'), (402006, '贵金属')], help_text='基金运作方式', verbose_name='投资标的类型代码')),
                ('underlying_asset_type', models.CharField(default='', help_text='基金运作方式', max_length=32, verbose_name='投资标的类型')),
                ('start_date', models.DateTimeField(blank=True, help_text='成立日期', null=True, verbose_name='成立日期')),
                ('end_date', models.DateTimeField(blank=True, help_text='结束日期', null=True, verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '基金主体信息',
                'verbose_name_plural': '基金主体信息',
            },
        ),
        migrations.CreateModel(
            name='Recommendfunds',
            fields=[
                ('code', models.CharField(default='', help_text='基金主体代码', max_length=12, primary_key=True, serialize=False, verbose_name='基金主体代码')),
                ('name', models.CharField(default='', help_text='基金名称', max_length=100, verbose_name='基金名称')),
                ('comment', models.CharField(default='', help_text='评价', max_length=200, verbose_name='评价')),
                ('total_return', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='回报率')),
            ],
        ),
        migrations.CreateModel(
            name='FundsNetvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(help_text='交易日', verbose_name='交易日')),
                ('net_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='单位净值')),
                ('sum_value', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=20, null=True, verbose_name='累计净值')),
                ('factor', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='复权因子')),
                ('acc_factor', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='累计复权因子')),
                ('refactor_net_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='累计复权净值')),
                ('daily_return', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='日收益')),
                ('month_return', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='月收益')),
                ('quarter_return', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='季收益')),
                ('total_return', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='总收益')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.FundMain', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金净值信息',
                'verbose_name_plural': '基金净值信息',
            },
        ),
    ]
