# Generated by Django 3.0.7 on 2020-12-25 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='描述')),
                ('status', models.IntegerField(choices=[(1, '关注'), (2, '取消关注')], help_text='基金状态', verbose_name='状态')),
                ('funds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfunds', to='funds.FundMain', verbose_name='基金代码')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '关注基金',
                'verbose_name_plural': '关注基金',
            },
        ),
        migrations.CreateModel(
            name='UsersManageFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='基金总规模')),
                ('fund_start', models.DateTimeField(help_text='基金开始日期', null=True, verbose_name='基金开始日期')),
                ('usersfunds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.UsersFunds', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '管理基金',
                'verbose_name_plural': '管理基金',
            },
        ),
        migrations.CreateModel(
            name='UsersInvestFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='基金份额')),
                ('enter_netvalue', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='买入基金净值')),
                ('enter_date', models.DateTimeField(help_text='买入基金日期', verbose_name='买入基金日期')),
                ('usersfunds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.UsersFunds', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '投资基金',
                'verbose_name_plural': '投资基金',
            },
        ),
    ]
