# Generated by Django 3.0.7 on 2020-12-26 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_manage', '0001_initial'),
        ('funds', '0002_usersfunds_usersinvestfunds_usersmanagefunds'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_id', to='news_manage.News', verbose_name='发布时间')),
                ('newsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_name_id', to='news_manage.News', verbose_name='新闻名称')),
                ('newsori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_id', to='news_manage.News', verbose_name='信息来源')),
                ('newsurl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_url_id', to='news_manage.News', verbose_name='新闻链接')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '关注新闻',
                'verbose_name_plural': '关注新闻',
            },
        ),
    ]
