# Generated by Django 3.0.7 on 2020-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_fundprotfolio_protfoliobond_protfoliostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundprotfolio',
            name='buying_back_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='买入返售金融资产占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='buying_back_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='买入返售金融资产金额'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='deposit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='银行存款和结算备付金合计占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='deposit_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='银行存款和结算备付金合计'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='derivative_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='金融衍生品投资占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='derivative_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='金融衍生品投资金额'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='equity_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='权益类投资占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='equity_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='权益类投资金额'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='fixed_income_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='固定收益投资占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='fixed_income_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='固定收益投资金额'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='others_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='其他资产占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='others_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='其他资产'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='precious_metal_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='贵金属投资占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='precious_metal_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='贵金属投资金额'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='stock_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='股票投资占比'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='stock_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='股票投资金额'),
        ),
        migrations.AlterField(
            model_name='fundprotfolio',
            name='total_asset',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='总资产合计'),
        ),
        migrations.AlterField(
            model_name='protfoliobond',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='持有债券的市值'),
        ),
        migrations.AlterField(
            model_name='protfoliobond',
            name='proportion',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='占净值比例'),
        ),
        migrations.AlterField(
            model_name='protfoliobond',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='持有债券数量'),
        ),
        migrations.AlterField(
            model_name='protfoliostock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='持有股票的市值'),
        ),
        migrations.AlterField(
            model_name='protfoliostock',
            name='proportion',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='占净值比例'),
        ),
        migrations.AlterField(
            model_name='protfoliostock',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='持有股票数量'),
        ),
    ]
